#?? ??
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/silverpotion
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    show_sql: true
  application:
    name: user-service
#  kafka:
#    bootstrap-servers: localhost:9092
#    group-id: my-consumer-group
#    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
cloud:
  aws:
    credentials:
      access-key: AKIAWCZC5QR3NLEWSPNX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: silverpotion

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 0
  #port?? 0?? ??? ??? ????? ???  port??

jwt:
#  be11-fin-010-SimverPotion-wearetheteamwecandoitbe11-fin-010-SimverPotion-wearetheteamwecandoitbe11-fin-010-SimverPotion-wearetheteamwecandoit
  secretKey: YmUxMS1maW4tMDEwLVNpbXZlclBvdGlvbi13ZWFyZXRoZXRlYW13ZWNhbmRvaXRiZTExLWZpbi0wMTAtU2ltdmVyUG90aW9uLXdlYXJldGhldGVhbXdlY2FuZG9pdGJlMTEtZmluLTAxMC1TaW12ZXJQb3Rpb24td2VhcmV0aGV0ZWFtd2VjYW5kb2l0
  expiration: 3000
#  kyungleader-leemaknae-choisharpboy-kimisme-wearetheteamandgothrougheverystagekyungleader-leemaknae-choisharpboy-kimisme-wearetheteamandgothrougheverystage
  secretKeyRt: a3l1bmdsZWFkZXItbGVlbWFrbmFlLWNob2lzaGFycGJveS1raW1pc21lLXdlYXJldGhldGVhbWFuZGdvdGhyb3VnaGV2ZXJ5c3RhZ2VreXVuZ2xlYWRlci1sZWVtYWtuYWUtY2hvaXNoYXJwYm95LWtpbWlzbWUtd2VhcmV0aGV0ZWFtYW5kZ290aHJvdWdoZXZlcnlzdGFnZQ==
#  200일
  expirationRt: 288000

openai:
  api-key: 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

logging:
  level:
    root: info
#    별도의 에러로그 없이, 날짜구분없이 모든로그를 남기는 설정
  file:
    name: logs/app.log
#포트원 결제 관련 키값들
imp:
  code: imp47183178
  access: 7168720802721558
  secret: t2AhyJMVDyBFN40RKrzgLB6mkX6SLQNNyzdecjDpTWIPD1CU19AVSU8UmNANGmCk1JlEBjZnUV6w3nrP

oauth:
  google:
    client-id: 73727762121-skf00kqrlnfjput7t493mmdifss29170.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:3000/oauth/google/redirect
  kakao:
    client-id: 740a1fc6969a1fc6c821d81a2236d3fe
    redirect-uri: http://localhost:3000/oauth/kakao/redirect
