apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: sp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: 418295678070.dkr.ecr.ap-northeast-2.amazonaws.com/silverpotion/chat:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: REDIS_HOST
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: DB_HOST
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: DB_PW
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: sp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: chat