apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sp-ingress
  namespace: sp
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: sp-issuer
spec:
  tls:
    - hosts:
        - "server.jy1187.shop"
      secretName: server-jy1187-com-tls
  rules:
    - host: server.jy1187.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sp-issuer
  namespace: sp
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rifkehtm862@gmail.com
    privateKeySecretRef:
      name: sp-issuer
    solvers:
      - http01:
          ingress:
            class: nginx
---
# 3.ClusterIssue를 사용하여 Certificate 리소스 생성 : Certificate리소스 생성시에 인증서 발급
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-jy1187-com-tls
  namespace: sp
spec:
  secretName: server-jy1187-com-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: sp-issuer
    kind: ClusterIssuer
  commonName: server.jy1187.shop
  dnsNames:
    - server.jy1187.shop