apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: sp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: 418295678070.dkr.ecr.ap-northeast-2.amazonaws.com/silverpotion/user:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: REDIS_HOST
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: DB_HOST
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: DB_PW
            - name: AWS_ACCESS
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: AWS_ACCESS
            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: AWS_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: JWT_SECRET
            - name: JWT_SECRET_RT
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: JWT_SECRET_RT
            - name: AI_KEY
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: AI_KEY
            - name: IMP_CODE
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: IMP_CODE
            - name: IMP_ACCESS
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: IMP_ACCESS
            - name: IMP_SECRET
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: IMP_SECRET
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: GOOGLE_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: GOOGLE_SECRET
            - name: KAKAO_ID
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: KAKAO_ID
            - name: COOLSMS_KEY
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: COOLSMS_KEY
            - name: COOLSMS_SECRET
              valueFrom:
                secretKeyRef:
                  name: sp-app-secrets
                  key: COOLSMS_SECRET
          readinessProbe:
            httpGet:
              path: /silverpotion/user/healthcheck
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: sp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: user