eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true

      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          filters:
            #            ??? ???? ???? user-service? ?????? ?
            - StripPrefix=1
          uri: lb://user-service
        - id: post-service
          predicates:
            - Path=/post-service/**
          filters:
            - StripPrefix=1
          uri: lb://post-service

