eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  config:
    activate:
      on-profile: local
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      #      CORS공통처리
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - https://www.jy1187.shop
            #              - https://d414-220-72-230-176.ngrok-free.app
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true
      routes:
        #        유저서비스
        - id: user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
          uri: lb://user-service
        #          포스트 서비스
        - id: post-service
          predicates:
            - Path=/post-service/**
          filters:
            - StripPrefix=1
          uri: lb://post-service
        #          챗 서비스
        - id: chat-service
          predicates:
            - Path=/chat-service/**
          filters:
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
          uri: lb://chat-service
        #          챗 서비스 웹소켓
        - id: chat-service-ws
          predicates:
            - Path=/chat-service/**
          filters:
            - StripPrefix=1
          uri: ws://chat-service


jwt:
  #  be11-fin-010-SimverPotion-wearetheteamwecandoitbe11-fin-010-SimverPotion-wearetheteamwecandoitbe11-fin-010-SimverPotion-wearetheteamwecandoit
  secretKey: YmUxMS1maW4tMDEwLVNpbXZlclBvdGlvbi13ZWFyZXRoZXRlYW13ZWNhbmRvaXRiZTExLWZpbi0wMTAtU2ltdmVyUG90aW9uLXdlYXJldGhldGVhbXdlY2FuZG9pdGJlMTEtZmluLTAxMC1TaW12ZXJQb3Rpb24td2VhcmV0aGV0ZWFtd2VjYW5kb2l0

