#RabbitMQ
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: sp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: sp
spec:
  selector:
    app: rabbit
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672