eureka:
  client:
    enabled: false
#유레카 설정 삭제 후 쿠버네티스 설정 추가
spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 10MB # 개별파일 최대 크기
      max-request-size: 100MB  # 전체 요청 최대 크기
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: ${REDIS_HOST}
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/silverpotion?useUnicode=true&characterEncoding=utf8mb4
    username: admin
    password: ${DB_PW}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    show_sql: true
  application:
    #   여기서는 쿠버네티스의 서비스 이름과 일치해야할 이름
    name: post-service
  kafka:
    bootstrap-servers: kafka-service:9092
    consumer:
      group-id: sse-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    kubernetes:
      discovery:
        enabled: true
  loadbalancer:
    mode: service

server:
  port: 8080
  #port?? 0?? ??? ??? ????? ???  port??
  # aws s3 계정 설정
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    region:
      static: ap-northeast-2
    s3:
      bucket: silverpotion

#opensearch:
#  host: ${OPENSEARCH_HOST}
#  port: 443
#  scheme: https
#  username: silverpotion
#  password: ${OPENSEARCH_PW}

