spring:
  servlet:
    multipart:
      max-file-size: 10MB # 개별파일 최대 크기
      max-request-size: 100MB  # 전체 요청 최대 크기
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/silverpotion
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    show_sql: true
  application:
    #   user-sevice?? ???? eureka? ??
    name: post-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: sse-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 0
  #port?? 0?? ??? ??? ????? ???  port??
  # aws s3 계정 설정
cloud:
  aws:
    credentials:
      access-key: AKIAWCZC5QR3NLEWSPNX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: silverpotion

#opensearch:
#  host: search-gathering-search-surdnnjq4pvdojukarr6575gsy.ap-northeast-2.es.amazonaws.com
#  port: 443
#  scheme: https
#  username: silverpotion
#  password: Qqqq1111!

